<?php include_once __DIR__ . '/../header.html'; ?>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3 class="text-center">Criar Post</h3>
            <form class="form-horizontal" method="post" action="/posts/store">
                <div class="form-group">
                    <label for="title" class="col-sm-2 control-label">Title</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="title" name="title" placeholder="Title">
                    </div>
                </div>
                <div class="form-group">
                    <label for="content" class="col-sm-2 control-label">Content</label>
                    <div class="col-sm-10">
                        <textarea rows="10" cols="10" class="form-control" id="content" name="content" placeholder="Content"></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">Criar Post</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<?php include_once __DIR__ . '/../footer.html'; ?>