<?php include_once __DIR__ . '/../header.html'; ?>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3 class="text-center">Lista de Posts</h3>
            <a href="/posts/create">Novo Post</a>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Title</th>
                            <th>Content</th>
                            <th>Editar</th>
                        </tr>   
                    </thead>
                    <tbody>
                        <?php foreach ($posts as $post) : ?>
                            <tr>
                                <td><?php echo $post->getId(); ?></td>
                                <td><?php echo $post->getTitle(); ?></td>
                                <td><?php echo $post->getContent(); ?></td>
                                <td>
                                    <a href="/posts/edit/<?php echo $post->getId(); ?>">Editar</a> |
                                    <a href="/posts/remove/<?php echo $post->getId(); ?>">Remove</a> |
                                    <a href="/posts/categories/<?php echo $post->getId(); ?>">Category</a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<?php include_once __DIR__ . '/../footer.html'; ?>