<?php include_once __DIR__ . '/../header.html'; ?>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3 class="text-center">Add Category</h3>
            <form class="form-horizontal" method="post" action="/posts/categories/store">
                <div class="form-group">
                    <label for="categories" class="col-sm-2 control-label">Categories</label>
                    <div class="col-sm-10">
                        <select class="form-control" name="categories[]" multiple>
                            <?php foreach($categories as $category) : ?>
                                <option value="<?php echo $category->getId(); ?>" <?php echo $posts->getCategories()->contains($category) ? "selected" : "" ?> >
                                    <?php echo $category->getName(); ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default">Add Category</button>
                    </div>
                </div>
                <input type="hidden" name="idPost" value="<?php echo $posts->getId(); ?>">
            </form>
        </div>
    </div>
</div>

<?php include_once __DIR__ . '/../footer.html'; ?>