<?php include_once __DIR__ . '/../header.html'; ?>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3 class="text-center">Lista de Categorias</h3>
            <a href="/categories/create">Nova Categoria</a>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Editar</th>
                        </tr>   
                    </thead>
                    <tbody>
                        <?php foreach ($categories as $category) : ?>
                            <tr>
                                <td><?php echo $category->getId(); ?></td>
                                <td><?php echo $category->getName(); ?></td>
                                <td><a href="/categories/edit/<?php echo $category->getId(); ?>">Editar</a> | <a href="/categories/remove/<?php echo $category->getId(); ?>">Remove</a></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<?php include_once __DIR__ . '/../footer.html'; ?>