<?php include_once __DIR__ . '/../header.html'; ?>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3 class="text-center">Editar Categoria</h3>
            <form class="form-horizontal" method="post" action="/categories/update">
                <div class="form-group">
                    <label for="name" class="col-sm-2 control-label">Name</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="name" name="name" placeholder="Name" value="<?php echo $category->getName(); ?>">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">Criar Categoria</button>
                    </div>
                </div>
                <input type="hidden" name="id" value="<?php echo $category->getId(); ?>">
            </form>
        </div>
    </div>
</div>

<?php include_once __DIR__ . '/../footer.html'; ?>