<?php include_once __DIR__ . '/header.html'; ?>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3 class="text-center">Posts do Blog</h3>

            <div class="col-md-8">
                <?php foreach($posts as $post) : ?>
                    <div class="jumbotron">
                        <h1><?= $post->getTitle() ?></h1>
                        <p><?= $post->getContent() ?></p>
                        <p><a class="btn btn-primary btn-lg" href="#" role="button">Leia Mais...</a></p>
                    </div>
                <?php endforeach; ?>
            </div>

            <div class="col-md-4">
                <ul class="list-group text-center">
                    <li class="list-group-item"><a href="/">Todos</a></li>
                    <?php foreach($categories as $category) : ?>
                        <li class="list-group-item"><a href="?search=<?= $category->getId() ?>"><?= $category->getName() ?></a></li>
                    <?php endforeach; ?>
                </ul>
            </div>

        </div>
    </div>
</div>

<?php include_once __DIR__ . '/footer.html'; ?>